version: '3.9'

services:
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      -  ../data:/var/lib/mysql

  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules